### ISSUE TITLE
Cannot read properties of undefined (reading 'session_id')

### ISSUE THREAD

**Issue by kenji-fire** [Tenpi/crunchyroll.ts#6]
Log:
```
/home/user/Downloads/node_modules/crunchyroll.ts/dist/API.js:102
                    API.sessionID = response.session_id;
                                             ^

TypeError: Cannot read properties of undefined (reading 'session_id')
    at /home/user/Downloads/node_modules/crunchyroll.ts/dist/API.js:102:46
    at step (/home/user/Downloads/node_modules/crunchyroll.ts/dist/API.js:63:23)
    at Object.next (/home/user/Downloads/node_modules/crunchyroll.ts/dist/API.js:44:53)
    at fulfilled (/home/user/Downloads/node_modules/crunchyroll.ts/dist/API.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Code:
```js
const crunchyroll_module = require("crunchyroll.ts");
const crunchyroll = crunchyroll_module.default;
const username = 'xxxx';
const password = 'xxxx!';

const useAPI = async () => {
    console.log('Login into account')
    const auth = await crunchyroll.login(username, password)
    console.log('auth', auth)

    console.log('Download')
    const video = await crunchyroll.util.downloadEpisode("https://www.crunchyroll.com/de/spy-x-family/episode-11-stella-843104", "./videos", {resolution: 720, quality: 16, preferSub: true}, videoProgress)
    console.log('video', video)

    const videoProgress = (progress, resume) => {
        console.log(`Time Marker: ${progress.timemark} Percent: ${progress.percent.toFixed(2)}`)
    }
}

useAPI();
```

**Comment by kenji-fire** [comment]
## When using TypeScript:

Logs:
```
user@user-pc:~/Downloads/spamDeny$ npm run dev

> spamdeny@1.0.0 dev
> ts-node-dev --exit-child src/index.ts

[INFO] 00:05:20 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.8.1, typescript ver. 4.7.4)
TypeError: Cannot read properties of undefined (reading 'session_id')
    at /home/user/Downloads/spamDeny/node_modules/crunchyroll.ts/dist/API.js:102:46
    at step (/home/user/Downloads/spamDeny/node_modules/crunchyroll.ts/dist/API.js:63:23)
    at Object.next (/home/user/Downloads/spamDeny/node_modules/crunchyroll.ts/dist/API.js:44:53)
    at fulfilled (/home/user/Downloads/spamDeny/node_modules/crunchyroll.ts/dist/API.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[ERROR] 00:05:21 TypeError: Cannot read properties of undefined (reading 'session_id')
Child got SIGTERM, exiting.
```

Index.ts:
```
import crunchyroll from "crunchyroll.ts"

const username = 'xxx';
const password = 'xxx';

async function useAPI() {
    const animeLink = await crunchyroll.anime.get("https://www.crunchyroll.com/anime-gataris/")
    console.log('animeLink', animeLink)
}
useAPI()
```

**Comment by Tenpi** [comment]
the access token used here https://github.com/Tenpi/crunchyroll.ts/blob/9e94bf9fb2870691dda2ec0f79bf5a4b5bd4fe12/API.ts#L25 got expired or revoked (?) but I don't know how to get a new one

**Comment by Tenpi** [comment]
Token updated
